import paramiko, sys
print('Trying SSH...')
try:
    c=paramiko.SSHClient()
    c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    c.connect('8.138.218.146',username='root',password='ww0987654.',timeout=15,banner_timeout=15)
    print('SSH OK!')
    sftp=c.open_sftp()
    f=open('D:/tokai/index-fixed2.html','r',encoding='utf-8')
    html=f.read(); f.close()
    f=sftp.open('/var/www/frontend/index.html','w')
    f.write(html); f.close()
    sftp.close()
    print('Uploaded %d bytes' % len(html))
    stdin,stdout,stderr=c.exec_command('nginx -s reload')
    err=stderr.read().decode()
    if err: print('nginx warning:',err)
    else: print('nginx reloaded!')
    stdin,stdout,stderr=c.exec_command("curl -s http://localhost/ | head -c 80")
    print('Page:', stdout.read().decode()[:80])
    c.close()
    print('DONE!')
except Exception as e:
    print('FAILED:',e)
